import React from 'react';
import type { Metadata } from 'next';
import '../styles/index.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => (
  <html lang='en'>
    <body className='page-layout'>
      {children}
    </body>
  </html>
);

export default RootLayout;
